#!/usr/bin/env node
// -*- mode: js2; -*-

/**
 * Run `git --no-pager log -1` in current or target directory
 *  xw tool last-commit-info [git_dir_or_current_dir]
 */

const cp = require('child_process');
const path = require('path');

let target_dir = '.';
if (process.argv.length >= 3) {
  target_dir = process.argv[2];
}
target_dir = path.resolve(target_dir);

cp.execFileSync('git', ['--no-pager', 'log', '-1'], {
  cwd: target_dir,
  stdio: 'inherit',
});
